# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: just-the-docs/just-the-docs

title: Websaw Examples and Tutorials
email: eudorajab1@gmail.com
logo: "/assets/images/websaw-logos_transparent.png"
aux_links:
  "Websaw on GitHub":
    - "//github.com/valq7711/websaw"
  "Pyjsaw on Github":
    - "//github.com/valq7711/websaw"
  "Voodoodal on Github":
    - "//github.com/valq7711/voodoodal"
   
search_enabled: true
search.heading_level: 2

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

markdown: kramdown

# Build settings
heading_anchors: true
footer_content: "Copyright &copy; 2020-2022 John Bannister." 
# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#3last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub."
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#theme: jekyll-theme-minimal
